# Generated by Django 5.0.7 on 2024-08-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_course_preview_image_and_more'),
        ('users', '0002_alter_user_options_remove_user_username_user_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('payment_amount', models.FloatField(help_text='Укажите сумму платежа', verbose_name='Сумма платежа')),
                ('payment_method', models.CharField(choices=[('tran', 'Перевод на счет'), ('cash', 'Наличными')], help_text='Укажите способ оплаты', max_length=4, verbose_name='Способ оплаты')),
                ('course_paid', models.ForeignKey(blank=True, help_text='Укажите оплаченный курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='Оплаченный курс')),
                ('lesson_paid', models.ForeignKey(blank=True, help_text='Укажите оплаченный урок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(help_text='Укажите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
