# Generated by Django 5.0.7 on 2024-08-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payment_link_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.PositiveIntegerField(help_text='Укажите сумму платежа', verbose_name='Сумма платежа'),
        ),
    ]
