# Generated by Django 5.0.7 on 2024-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/course/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/lesson/'),
        ),
    ]
